# vim ft=yaml
# travis-ci.org definition for Fail2Ban build
language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install:
  - "pip install pyinotify"
script:
    - (set -e; for s in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23; do python ./fail2ban-testcases -l debug -t test_move_file; done; )
